### ISSUE TITLE
mark most recent release as latest

### ISSUE THREAD

**Issue by stu247** [rhasspy/wyoming-piper#15]
Please mark the most recent release of wyoming-piper (currently v1.5.2) as the "Latest" release.  See (https://github.com/rhasspy/wyoming-faster-whisper) as an example; it has the Latest release set to v2.2.0.

This would allow people to monitor for changes in HA via:

```
rest:
  - resource: https://api.github.com/repos/rhasspy/wyoming-piper/releases/latest
    scan_interval: 21600  # 6 hrs
    sensor:
      - name: "Piper Latest Version"
        value_template: "{{ value_json.tag_name }}"
```
