### ISSUE TITLE
Possible to synthesize speech via http request? 

### ISSUE THREAD

**Issue by jereskuta** [rhasspy/wyoming-piper#9]
Documentation doesn't tell me, if its possible to use piper via http requests. I have wyoming piper running in a separate server and home assistant is able to use it just fine. 

I would like to use the tts functionality with another project as well by sending http request with the text and playing the output file in my program.

I think this is how home assistant is using piper so it should be possible?

**Comment by jerblack** [comment]
You can do this with a Home Assistant automation using the webhook trigger. Here's how I do the same thing:
```
alias: speak webhook
description: ""
trigger:
  - platform: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: speak
condition: []
action:
  - service: tts.speak
    target:
      entity_id: tts.piper
    data:
      cache: true
      media_player_entity_id: media_player.snapcast_tts
      message: |
        {{ trigger.json.text }}
mode: queued
```
And then I can POST text to that endpoint and Piper will speak the text through my Snapcast server.
```
curl -H "Content-Type: application/json" -X POST http://homeassistant.local:8123/api/webhook/speak -d '{"text":"the time is 3 12 pm"}'
```
